exclude:
  - README.md
  - CNAME
  - LICENSE
  - font/fontello-config.json
sass:
  sass_dir: _sass
  style: compressed
title: That 1 Painter
phone: 512-373-0002
email: steven@that1painter.com
facebook: https://www.facebook.com/pages/That-1-Painter/120820088018007
yelp: http://www.yelp.com/biz/that-1-painter-austin
description: >
  A painting company owned and operated by Steven Montgomery and based in
  Austin, Texas.
